---
- name: Converge
  hosts: all
  vars:
    fwr__rules:
      - chain: INPUT
        protocol: tcp
        destination_port: 1337
        jump: DROP
      - chain: INPUT
        protocol: tcp
        ip_version: ipv6
        source: '2600::'
        jump: DROP
  roles:
    - name: ansible-role-firewall-rule
